#!/bin/bash -x

# write to file
overwrite_to_file()
{

  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-a.yml.php" > "db/schemes/b4t-classic-a.yml"
  base16-builder --scheme "db/schemes/b4t-classic-a.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-a-dark.itermcolors" 
  base16-builder --scheme "db/schemes/b4t-classic-a.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-a-light.itermcolors" 
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-b.yml.php" > "db/schemes/b4t-classic-b.yml"
  base16-builder --scheme "db/schemes/b4t-classic-b.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-b-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-b.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-b-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-c.yml.php" > "db/schemes/b4t-classic-c.yml"
  base16-builder --scheme "db/schemes/b4t-classic-c.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-c-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-c.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-c-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-d.yml.php" > "db/schemes/b4t-classic-d.yml"
  base16-builder --scheme "db/schemes/b4t-classic-d.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-d-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-d.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-d-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-e.yml.php" > "db/schemes/b4t-classic-e.yml"
  base16-builder --scheme "db/schemes/b4t-classic-e.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-e-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-e.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-e-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-f.yml.php" > "db/schemes/b4t-classic-f.yml"
  base16-builder --scheme "db/schemes/b4t-classic-f.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-f-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-f.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-f-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-i.yml.php" > "db/schemes/b4t-classic-i.yml"
  base16-builder --scheme "db/schemes/b4t-classic-i.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-i-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-i.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-i-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-l.yml.php" > "db/schemes/b4t-classic-l.yml"
  base16-builder --scheme "db/schemes/b4t-classic-l.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-l-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-l.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-l-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-o.yml.php" > "db/schemes/b4t-classic-o.yml"
  base16-builder --scheme "db/schemes/b4t-classic-o.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-o-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-o.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-o-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-p.yml.php" > "db/schemes/b4t-classic-p.yml"
  base16-builder --scheme "db/schemes/b4t-classic-p.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-p-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-p.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-p-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-q.yml.php" > "db/schemes/b4t-classic-q.yml"
  base16-builder --scheme "db/schemes/b4t-classic-q.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-q-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-q.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-q-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-r.yml.php" > "db/schemes/b4t-classic-r.yml"
  base16-builder --scheme "db/schemes/b4t-classic-r.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-r-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-r.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-r-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-s.yml.php" > "db/schemes/b4t-classic-s.yml"
  base16-builder --scheme "db/schemes/b4t-classic-s.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-s-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-s.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-s-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-t.yml.php" > "db/schemes/b4t-classic-t.yml"
  base16-builder --scheme "db/schemes/b4t-classic-t.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-t-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-t.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-t-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-u.yml.php" > "db/schemes/b4t-classic-u.yml"
  base16-builder --scheme "db/schemes/b4t-classic-u.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-u-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-classic-u.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-u-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-classic-w.yml.php" > "db/schemes/b4t-classic-w.yml"
  base16-builder --scheme "db/schemes/b4t-classic-w.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-classic-w-dark.itermcolors" 
  base16-builder --scheme "db/schemes/b4t-classic-w.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-classic-w-light.itermcolors" 
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-modern-c.yml.php" > "db/schemes/b4t-modern-c.yml"
  base16-builder --scheme "db/schemes/b4t-modern-c.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-modern-c-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-modern-c.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-modern-c-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-modern-n.yml.php" > "db/schemes/b4t-modern-n.yml"
  base16-builder --scheme "db/schemes/b4t-modern-n.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-modern-n-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-modern-n.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-modern-n-light.itermcolors"
  curl "http://localhost/~bram/github.com/atelierbram/base4tone-iterm2/db/schemes/b4t-modern-w.yml.php" > "db/schemes/b4t-modern-w.yml"
  base16-builder --scheme "db/schemes/b4t-modern-w.yml" --template "db/templates/iterm2/dark.ejs" > "ColorPresets/base4tone-modern-w-dark.itermcolors"
  base16-builder --scheme "db/schemes/b4t-modern-w.yml" --template "db/templates/iterm2/light.ejs" > "ColorPresets/base4tone-modern-w-light.itermcolors"
 }

# execute it
overwrite_to_file
